spring:
    application:
        name: demo-service
    data:
        mongodb:
            uri: ${MONGO_URI}
    redis:
        database: 0
        host: ${REDIS_HOST}
        port: ${REDIS_PORT}
        timeout: 60000
        key: demo-messages

kafka:
    bootstrapAddress: ${KAFKA_BOOTSTRAP_SERVER}
    groupId: demo
    topicName:  demo-topic